// Shared icon name type — must match the keys in the webview's
// ICON_PATHS registry. Duplicated here (rather than imported) so
// the backend doesn't pull in the React webview module graph.
export type IconName =
  | "sparkle"
  | "send"
  | "plus"
  | "check"
  | "x"
  | "chevronR"
  | "chevronD"
  | "chevronL"
  | "chevronU"
  | "file"
  | "folder"
  | "search"
  | "terminal"
  | "branch"
  | "edit"
  | "code"
  | "at"
  | "attach"
  | "dots"
  | "history"
  | "bolt"
  | "shield"
  | "shieldOff"
  | "layers"
  | "book"
  | "arrow"
  | "play"
  | "stop"
  | "cloud"
  | "lock"
  | "eye"
  | "copy"
  | "user"
  | "settings"
  | "zap"
  | "git"
  | "refresh"
  | "logout";
